# $OpenBSD$

COMMENT= 		embedded documentation in C++
CATEGORIES=		x11 x11/kde devel
VERSION=		2.0a54
DISTNAME=		kdoc-${VERSION}

MASTER_SITES=		http://distfiles.bsdfrog.org/

MODULES=	
AUTOCONF_VERSION=	2.52
CONFIGURE_STYLE=	autoconf no-autoheader
USE_GMAKE=		No
USE_GROFF =	Yes
MODGNU_CONFIG_GUESS_DIRS=${WRKSRC}

.include <bsd.port.mk>
