# $OpenBSD$

COMMENT=		common time and date operations with GPS operations

DISTNAME=		DateTime-Precise-1.05
CATEGORIES=		devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan

.include <bsd.port.mk>
