# $OpenBSD$

COMMENT =	multi-author documents
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	nodeaccess_userreference-6.x-3.3
PKGNAME =	drupal6-node-access-user-reference-3.3
RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
