# $OpenBSD$

COMMENT =	node based bulk operations displayed by a view

DISTNAME = 	views_bulk_operations-6.x-1.12
PKGNAME =	drupal6-views_bulk_operations-1.12
REVISION =	0

RUN_DEPENDS =	www/drupal6/views

.include <bsd.port.mk>
