# $OpenBSD$

COMMENT =	Fast, Nimble PDF Generation For Ruby -- ruby-prawn

DISTNAME =	prawn-${VERSION}
REVISION =	4

RUN_DEPENDS =	textproc/ruby-prawn/core,${MODRUBY_FLAVOR} \
		textproc/ruby-prawn/layout,${MODRUBY_FLAVOR} \
		textproc/ruby-prawn/format,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
