# $OpenBSD$

COMMENT=	interactive geometry program, documentation

DISTNAME=	drgeo-doc-1.6
REVISION=	0
CATEGORIES=	education math

HOMEPAGE=	http://www.ofset.org/drgeo/

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	http://documentation.ofset.org/drgeo/

CONFIGURE_STYLE=	gnu

NO_BUILD=Yes

.include <bsd.port.mk>
