# $OpenBSD$

COMMENT =	whois client interface for perl5

MODULES =	cpan
DISTNAME =	Net-XWhois-0.90
REVISION =	0
CATEGORIES =	net

HOMEPAGE =	http://sourceforge.net/projects/xwhois/
MAINTAINER =	Johan Huldtgren <jhuldtgren@gmail.com>

# GPL/Artistic
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

.include <bsd.port.mk>
