# $OpenBSD$

COMMENT=	object-oriented wrapper around vec()

MODULES=	cpan
DISTNAME=	Bit-Vector-Minimal-1.3
REVISION=	1
CATEGORIES=	devel
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
