# $OpenBSD$

COMMENT =	theme framework with support for responsive web design

DISTNAME = 	adaptivetheme-7.x-2.3
PKGNAME =	drupal7-theme-adaptivetheme-2.3

MAINTAINER =	Jasper Lievisse Adriaanse <jasper@openbsd.org>

MODDRUPAL_THEME = Yes

.include <bsd.port.mk>
