# $OpenBSD$

COMMENT=	md5-based passwords in perl

MODULES=	cpan
DISTNAME=	Crypt-PasswdMD5-1.3
REVISION=	0
CATEGORIES=	security
USE_GROFF =	Yes

# beer-ware
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>	
