# $OpenBSD$
# $FreeBSD: Makefile,v 1.13 1997/01/03 00:40:55 max Exp $
#

    SUBDIR =
    SUBDIR += bash
    SUBDIR += es
    SUBDIR += perlsh
    SUBDIR += sash
    SUBDIR += scsh
    SUBDIR += tcsh
    SUBDIR += zoidberg
    SUBDIR += zsh

.include <bsd.port.subdir.mk>
