# $OpenBSD$

    SUBDIR =
    SUBDIR += bash
    SUBDIR += es
    SUBDIR += osh
    SUBDIR += nsh
    SUBDIR += perlsh
    SUBDIR += sash
    SUBDIR += scsh
    SUBDIR += tcsh
    SUBDIR += zoidberg
    SUBDIR += zsh

.include <bsd.port.subdir.mk>
