# $OpenBSD$

COMMENT =	mailer functionality for Merb

DISTNAME =	merb-mailer-${VERSION}
REVISION =	1

RUN_DEPENDS =	www/ruby-merb/core,${MODRUBY_FLAVOR}${MERB_REL_VER_SPEC} \
		mail/ruby-mailfactory,${MODRUBY_FLAVOR}>=1.2.3

.include <bsd.port.mk>
