# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	stock_supply_production

RUN_DEPENDS =	productivity/tryton/product \
		productivity/tryton/stock \
		productivity/tryton/production \
		productivity/tryton/stock_supply

.include <bsd.port.mk>
