# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	module for easy date and time manipulation

MODULES=	cpan
DISTNAME=	Class-Date-1.1.9
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
