# $OpenBSD$

COMMENT =	flexible, semantically correct XHTML theme for drupal
DISTNAME=	zen-6.x-2.0
PKGNAME =	drupal6-theme-zen-2.0
REVISION =	2

HOMEPAGE =	http://drupal.org/project/zen

RUN_DEPENDS =	www/drupal6/themesettingsapi
MODDRUPAL_THEME = Yes

.include <bsd.port.mk>
