# $OpenBSD$

    SUBDIR =
    SUBDIR += core
    SUBDIR += mm
    SUBDIR += plugins-base
    SUBDIR += plugins-ffmpeg
    SUBDIR += plugins-gl
    SUBDIR += plugins-good
    SUBDIR += plugins-ugly
    SUBDIR += plugins-bad
    SUBDIR += py-gstreamer

.include <bsd.port.subdir.mk>
