# $OpenBSD$

COMMENT =	charset Informations for MIME

DISTNAME =	MIME-Charset-1.009.1
CATEGORIES =	mail

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =	cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
