# $OpenBSD$

VERSION =		0.1.4
COMMENT =		collaboration services library
DISTNAME =		attica-${VERSION}
MASTER_SITES?=	${MASTER_SITE_KDE:=stable/attica/}
SHARED_LIBS =		attica 0.0

WANTLIB +=	m stdc++ lib/qt4/QtNetwork

.include <bsd.port.mk>
