# $OpenBSD$

COMMENT =	redirect login screen to https
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	securelogin-6.x-1.x-dev
PKGNAME =	drupal6-securelogin-1
REVISION =	1

.include <bsd.port.mk>
