# $OpenBSD$

COMMENT=	class for generating HTML form select elements for PHP

DISTNAME=	HTML_Select-1.2.1
REVISION=	2
CATEGORIES=	www

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
