# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	interface for cyclic redundancy check generation

MODULES=	cpan
DISTNAME=	String-CRC32-1.4
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

WANTLIB += c

.include <bsd.port.mk>
