# $OpenBSD$

COMMENT =		rspec expectations and matchers
DISTNAME =		rspec-expectations-2.7.0

BUILD_DEPENDS = 	${RUN_DEPENDS}
RUN_DEPENDS =		devel/ruby-diff-lcs,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
