# $OpenBSD$

COMMENT =	cryptographic CipherSaber encryption

DISTNAME =	Crypt-CipherSaber-1.00
REVISION =	0
CATEGORIES =	security

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =	cpan
USE_GROFF =	Yes
REGRESS_DEPENDS =	devel/p5-Test-Warn

.include <bsd.port.mk>
