# $OpenBSD$

COMMENT =	provide HAML support for Merb

DISTNAME =	merb-haml-${VERSION}
REVISION=	0

RUN_DEPENDS =	www/ruby-merb/core,${MODRUBY_FLAVOR}${MERB_REL_VER_SPEC} \
		textproc/ruby-haml,${MODRUBY_FLAVOR}>=2.0.3

.include <bsd.port.mk>
