# $OpenBSD$

COMMENT=	perl module to generate recursive descent parsers

MODULES=	cpan
DISTNAME=	Parse-RecDescent-1.965001
CATEGORIES=	devel perl5
USE_GROFF=	Yes

# Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
