# $OpenBSD$

COMMENT=	Italian language stemming

MODULES=	cpan
DISTNAME=	Lingua-Stem-It-0.02
CATEGORIES=	textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
