# $OpenBSD$

COMMENT =		perl extension for wait3 system call

SHARED_ONLY =		Yes
MODULES =		cpan
DISTNAME =		Proc-Wait3-0.03
REVISION =		0
CATEGORIES =		sysutils
MAINTAINER =		Abel Abraham Camarillo Ojeda <acamari@verlet.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB += c

.include <bsd.port.mk>
