# $OpenBSD$

COMMENT=	formatter for spellchecking pod

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	Pod-Spell-1.01
REVISION=	4
CATEGORIES=	textproc

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
