# $OpenBSD$

COMMENT=	GNUstep file transfer protcol tool

DISTNAME=	FTP-0.3
CATEGORIES=	net

HOMEPAGE=	http://gap.nongnu.org/ftp/
MASTER_SITES=	${MASTER_SITE_SAVANNAH:=gap/}

MODULES=	x11/gnustep
WANTLIB +=	c m pthread

.include <bsd.port.mk>
