# $OpenBSD$

     SUBDIR =
     SUBDIR += devel
     SUBDIR += devel,lua
     SUBDIR += devel,passenger
     SUBDIR += stable
     SUBDIR += stable,lua
     SUBDIR += stable,passenger

.include <bsd.port.subdir.mk>
