# $OpenBSD$

COMMENT=	perl extension for parsing ASCIIMathML text into MathML

DISTNAME=	Text-ASCIIMathML-0.81
CATEGORIES=	textproc
MODULES=	cpan
USE_GROFF =	Yes

CPAN_AUTHOR=	NODINE

MAINTAINER=	Okan Demirmen <okan@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
