# $OpenBSD$

COMMENT =		strict data types and String IO

DISTNAME =		strict-0.3.2
CATEGORIES =		devel

MAINTAINER =		Matthias Kilian <kili@openbsd.org>

HOMEPAGE =		http://www.cse.unsw.edu.au/~rl/code/strict.html

# BSD3
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
