# $OpenBSD$

COMMENT =		binary tools
DISTNAME =		binutils-2.22
CATEGORIES =		sysutils

HOMEPAGE =		http://www.gnu.org/software/binutils/

# GPLv3
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

#WANTLIB =		???

MASTER_SITES =		${MASTER_SITE_GNU:=binutils/}

#MODULES =		???
#BUILD_DEPENDS =	???
#RUN_DEPENDS =		???
#LIB_DEPENDS =		???
#REGRESS_DEPENDS =	???

#MAKE_FLAGS =		???
#MAKE_ENV =		???

SEPARATE_BUILD =	Yes
CONFIGURE_STYLE =	gnu
#CONFIGURE_ARGS +=	${CONFIGURE_SHARED}
#CONFIGURE_ENV =	???

#CFLAGS =		???
#LDFLAGS =		???

.include <bsd.port.mk>
