# $OpenBSD$

COMMENT=	Perl extension for Consistent Signal Handling

DISTNAME=	Sys-SigAction-0.11
CATEGORIES=	devel

# Perl
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

MODULES=	cpan

CONFIGURE_STYLE= perl
USE_GROFF =	Yes

.include <bsd.port.mk>
