# $OpenBSD$

COMMENT=		manifulate the Penn Treebank format

DISTNAME=		Lingua-Treebank-0.16
REVISION=		0
CATEGORIES=		textproc

# perl
PERMIT_DISTFILES_FTP=   Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_PACKAGE_CDROM=   Yes

MODULES=		cpan
USE_GROFF =		Yes

.include <bsd.port.mk>
