# $OpenBSD$

COMMENT=	xpath matching for object trees

MODULES=	cpan
DISTNAME=	Class-XPath-1.4
REVISION=	0
CATEGORIES=	devel textproc
USE_GROFF =	Yes

MAINTAINER=	Sam Smith <s@msmith.net>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
