# $OpenBSD$

COMMENT =	extensible architecture for authentication

DISTNAME =	merb-auth-1.1.1
REVISION =	1

RUN_DEPENDS =	www/ruby-merb/auth-core,${MODRUBY_FLAVOR}>=1.1.1,<1.2 \
		www/ruby-merb/auth-more,${MODRUBY_FLAVOR}>=1.1.1,<1.2 \
		www/ruby-merb/auth-slice-password,${MODRUBY_FLAVOR}>=1.1.1,<1.2 \
		www/ruby-merb/core,${MODRUBY_FLAVOR}>=1.1,<2.0

.include <bsd.port.mk>
