# $OpenBSD$

COMMENT=	Portuguese language stemming

MODULES=	cpan
DISTNAME=	Lingua-PT-Stemmer-0.01
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
