# $OpenBSD$

EX_LIST=	${EXAMPLES}

all:
	@for I in ${EX_LIST}; \
	  do (cd $$I; echo "==> Building for $$I"; \
	    qmake4 $$I.pro && env LOCALBASE=${LOCALBASE} gmake; \
            echo "";); \
	done

clean:
	@for I in ${EX_LIST}; \
	  do (cd $$I; echo "==> Cleaning for $$I"; \
	    gmake distclean; \
	    rm -Rf obj; \
	    rm -Rf moc; \
	    echo "";); \
	done

