# $OpenBSD$

COMMENT =	tetris like puzzle game

DISTNAME =	LapisPuzzle-1.2
CATEGORIES =	games

HOMEPAGE =	http://gap.nongnu.org/lapispuzzle/
MASTER_SITES =	${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB += 	c m pthread

.include <bsd.port.mk>
