# $OpenBSD$

COMMENT =	zap duplicate content through redirects
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	globalredirect-6.x-1.4
PKGNAME =	drupal6-globalredirect-1.4

.include <bsd.port.mk>
