# $OpenBSD$

COMMENT=		module for capturing output

MODULES=		cpan
DISTNAME=		IO-Capture-0.05
REVISION=		1
CATEGORIES=		devel
USE_GROFF =		Yes

MAINTAINER=		Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
