# $OpenBSD$

COMMENT=	data tables useful for parsing HTML

MODULES=	cpan
DISTNAME=	HTML-Tagset-3.20
REVISION=	0
CATEGORIES=	www
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
