# $OpenBSD$

PREFIX =		/usr

COMMENT =		map a directory hierarchy
DISTNAME =		mtree-20120506
CATEGORIES =		sysutils

#HOMEPAGE =		???	URL

# 2, 3 and 4-clause BSD licenses
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

#WANTLIB =		???

MASTER_SITES =		${MASTER_SITE_OBSCURE}

#MODULES =		???
#BUILD_DEPENDS =	???
#RUN_DEPENDS =		???
#LIB_DEPENDS =		???
#REGRESS_DEPENDS =	???

MAKE_FLAGS =		docdir=${PREFIX}/share/doc/mtree
#MAKE_ENV =		???

SEPARATE_BUILD =	Yes
#USE_GROFF =		Yes
CONFIGURE_STYLE =	gnu
#CONFIGURE_ARGS +=	${CONFIGURE_SHARED}
#CONFIGURE_ENV =	???

NO_REGRESS =		Yes

#CFLAGS =		???
#LDFLAGS =		???

.include <bsd.port.mk>
