# $OpenBSD$

COMMENT=	MySQL representations for Time::Piece objects

MODULES=	cpan
DISTNAME=	Time-Piece-MySQL-0.06
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
