# $OpenBSD$

COMMENT=	SNMP network management library for Ruby

DISTNAME=	snmp-1.0.2
REVISION=	5
CATEGORIES=	net

# bsd/ruby
PERMIT_PACKAGE_CDROM=	yes
PERMIT_PACKAGE_FTP=	yes
PERMIT_DISTFILES_CDROM=	yes
PERMIT_DISTFILES_FTP=	yes

MODULES=	lang/ruby

CONFIGURE_STYLE=ruby gem

.include <bsd.port.mk>
