# $OpenBSD$

COMMENT=		handle multiple file handles

MODULES=		cpan
DISTNAME=		IO-Multiplex-1.13
CATEGORIES=		devel

MAINTAINER=		Giovanni Bechis <giovanni@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
