# $OpenBSD$

COMMENT=	module to read a file starting at the end

MODULES=	cpan
DISTNAME=	File-ReadBackwards-1.05
CATEGORIES=	devel

MAINTAINER=	William Yodlowsky <william@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
