# $OpenBSD$

COMMENT= 	run perl program as a daemon process

MODULES=	cpan
DISTNAME=	Proc-Daemon-0.14
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=	sysutils/p5-Proc-ProcessTable

.include <bsd.port.mk>
