# $OpenBSD$

SHARED_ONLY =	Yes

COMMENT =	control over the flow of time

MODULES =	cpan
DISTNAME =	Time-Warp-0.5
REVISION =	0
CATEGORIES =	devel

# same as perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB += c

.include <bsd.port.mk>
