# $OpenBSD$

COMMENT=		parse and manipulate DNS Zone files

MODULES=		cpan
DISTNAME=		DNS-ZoneParse-1.10
CATEGORIES=		net
USE_GROFF =		Yes

MAINTAINER=		Girish Venkatachalam <girish1729@gmail.com>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
