# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	project_revenue
REVISION =		0

RUN_DEPENDS =		productivity/tryton/project \
			productivity/tryton/product \
			productivity/tryton/timesheet

.include <bsd.port.mk>
