# $OpenBSD$

COMMENT=	extracts embedded tests and code examples from pod

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	Pod-Tests-1.19
CATEGORIES=	textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
