# $OpenBSD$

COMMENT =	database introspection
MAINTAINER =	Marc Espie <espie@openbsd.org>

CATEGORIES += 	devel
DISTNAME = 	schema-7.x-1.0-beta3
PKGNAME =	drupal7-schema-1.0beta3

.include <bsd.port.mk>
