# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	perl module for parsing XML documents

MODULES=	cpan
DISTNAME=	XML-Parser-2.41
REVISION=	0
CATEGORIES=	textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB += c expat

.include <bsd.port.mk>
