# $OpenBSD$

COMMENT =		check Uniform Resource Identifiers

DISTNAME =		Test-URI-1.08
REVISION =		0
CATEGORIES =		devel

MODULES =		cpan
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =	Yes

RUN_DEPENDS =		www/p5-URI

.include <bsd.port.mk>
