# $OpenBSD$

COMMENT =	panels custom layouts
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	panels-6.x-3.10
PKGNAME =	drupal6-panels-3.10

RUN_DEPENDS =	www/drupal6/ctools

.include <bsd.port.mk>
