# $OpenBSD$

    SUBDIR =
.for i in gsm alaw ulaw sln16 wav # g722 g729 siren7 siren14
    SUBDIR += en,$i
    SUBDIR += en_AU,$i
    SUBDIR += es,$i
    SUBDIR += fr,$i
    SUBDIR += ru,$i
.endfor

.include <bsd.port.subdir.mk>
