# $OpenBSD$

COMMENT =	cck field that references a role
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	rolereference-6.x-1.3
PKGNAME =	drupal6-role-reference-1.3

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
