# $OpenBSD$

COMMENT=	perl module for manipulating PDF files

MODULES=	cpan
DISTNAME=	PDF-Reuse-0.33
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

MAINTAINER=	Sam Smith <S@mSmith.net>

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
