# $OpenBSD$

COMMENT =	image manipulation and cache
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	imagecache-6.x-2.0-beta12
PKGNAME =	drupal6-imagecache-2.0beta12
RUN_DEPENDS =	www/drupal6/imageapi

.include <bsd.port.mk>
