# $OpenBSD$

COMMENT=	GkrellM2 plugin to monitor wi(4) signal strength

DISTNAME=	gkrellmwireless-2.0.3
REVISION=	7
CATEGORIES=	net

HOMEPAGE=	http://gkrellm.luon.net/gkrellmwireless.php

MASTER_SITES=	http://gkrellm.luon.net/files/

WRKDIST=	${WRKDIR}/gkrellmwireless
PLUGIN=		${WRKSRC}/wireless.so

.include <bsd.port.mk>
