#!/bin/ksh 
#
# $OpenBSD$

JAVA_CMD=$(javaPathHelper -c clojure)

rlwrap -f ${TRUEPREFIX}/clojure/clj_completions ${JAVA_CMD} -classpath \
	${LOCALBASE}/share/java/classes/'*':${TRUEPREFIX}/clojure/clojure.jar:src:. \
        clojure.main "$@"
