# $OpenBSD$

     SUBDIR =
     SUBDIR += geda
     SUBDIR += gnome
     SUBDIR += gnustep
     SUBDIR += haskell-platform
     SUBDIR += msp430
     SUBDIR += obscure
     SUBDIR += xfce

.include <bsd.port.subdir.mk>
