# $OpenBSD$

COMMENT =		BMP/ICO decoding library

NETSURF_PROJECT =	libnsbmp
NETSURF_VERSION =	0.0.3

WRKDIST =		${WRKDIR}/${DISTNAME}

CATEGORIES =		graphics
SHARED_LIBS =		nsbmp 0.0 #0.0.3

.include <bsd.port.mk>
