# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT= 	interface to the DES encryption algorithm

MODULES=	cpan
DISTNAME=	Crypt-DES-2.05
REVISION=	3
CATEGORIES=	security
USE_GROFF =	Yes

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>	
