# $OpenBSD$

COMMENT =	run drupal scheduled tasks from apache
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	poormanscron-6.x-2.2
PKGNAME =	drupal6-poormanscron-2.2
REVISION =	0

.include <bsd.port.mk>
