# $OpenBSD$

COMMENT = 	manage process id files

MODULES =	cpan
DISTNAME =	Proc-PID-File-1.27
CATEGORIES =	devel

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
