# $OpenBSD$

    SUBDIR =
    SUBDIR += core

    SUBDIR += aggregates
    SUBDIR += migrations
    SUBDIR += constraints
    SUBDIR += serializer
    SUBDIR += sweatshop
    SUBDIR += timestamps
    SUBDIR += transactions
    SUBDIR += types
    SUBDIR += validations

    SUBDIR += data_mapper

.include <bsd.port.subdir.mk>
