# $OpenBSD$

TRYTOND_MODULE =	account_invoice
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account_product \
			productivity/tryton/currency \
			productivity/tryton/party

.include <bsd.port.mk>
