# $OpenBSD$

COMMENT =	provide support for ActionArgs

DISTNAME =	merb-action-args-${VERSION}
REVISION =	1

RUN_DEPENDS =	www/ruby-merb/core,${MODRUBY_FLAVOR}${MERB_REL_VER_SPEC} \
		devel/ruby-ruby2ruby,${MODRUBY_FLAVOR}>=1.1.9 \
		devel/ruby-parsetree,${MODRUBY_FLAVOR}>=2.1.1

.include <bsd.port.mk>
