# $OpenBSD$

COMMENT= 	tests strings for equality

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	Test-LongString-0.15
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
