# $OpenBSD$

PKG_ARCH =      *

COMMENT=	scripts libquvi uses for parsing the media details

DISTNAME=	libquvi-scripts-0.4.1
REVISION=	2

MODULES=	lang/lua

CONFIGURE_ARGS+=--with-nsfw

.include <bsd.port.mk>
