# $OpenBSD$

COMMENT =	date cck and api for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	date-6.x-2.9
PKGNAME =	drupal6-date-2.9

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
