# $OpenBSD$

COMMENT=	superclass for representing nodes in a tree

MODULES=	cpan
DISTNAME=	Tree-DAG_Node-1.06
CATEGORIES=	devel
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
