# $OpenBSD$

SHARED_ONLY=		Yes

COMMENT=		module to fetch the size of the terminal

MODULES=		cpan
DISTNAME=		Term-Size-0.207
REVISION=		0
CATEGORIES=		devel

# Perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

WANTLIB += c

.include <bsd.port.mk>
