# $OpenBSD$

COMMENT =	boolean support for Perl

MODULES =	cpan
DISTNAME =	boolean-0.27
CATEGORIES =	devel

MAINTAINER =	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

CPAN_AUTHOR =	INGY

.include <bsd.port.mk>
