# $OpenBSD$

COMMENT=	utilities for PostScript Type 1 fonts
DISTNAME=	t1utils-1.37
CATEGORIES=	print fonts

HOMEPAGE=	http://www.lcdf.org/~eddietwo/type/

# mix of BSD/GPL/PD
PERMIT_PACKAGE_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes

MASTER_SITES=	${HOMEPAGE}

WANTLIB=	c

CONFIGURE_STYLE=gnu

.include <bsd.port.mk>
