# $OpenBSD$

COMMENT =	classy 3-columns theme
DISTNAME=	danland-7.x-1.0
PKGNAME =	drupal7-theme-danland-1.0

HOMEPAGE =	http://drupal.org/project/danland

#RUN_DEPENDS =	www/drupal6/themesettingsapi
MODDRUPAL_THEME = Yes

.include <bsd.port.mk>
