# $OpenBSD$

COMMENT =	javascript-enhanced persistant menus for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	dhtml_menu-6.x-3.5
PKGNAME =	drupal6-dhtml-menu-3.5
REVISION =	0

.include <bsd.port.mk>
