# $OpenBSD$

COMMENT=	use regular expressions as hash keys

MODULES=	cpan
DISTNAME=	Tie-RegexpHash-0.15
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
