# $OpenBSD$

COMMENT =		perl framework for SIP

DISTNAME =		Net-SIP-0.67

CATEGORIES =		net telephony

MAINTAINER =		Alexander Bluhm <bluhm@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan
RUN_DEPENDS =		net/p5-Net-DNS>=0.56

.include <bsd.port.mk>
