# $OpenBSD$

COMMENT=	Porters stemming algorithm for Denmark

MODULES=	cpan
DISTNAME=	Lingua-Stem-Snowball-Da-1.01
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
