# $OpenBSD$

COMMENT =		fast, primitive HTTP request parser

SHARED_ONLY =		Yes
MODULES =		cpan
DISTNAME =		HTTP-Parser-XS-0.13
REVISION =		0
CATEGORIES =		www
MAINTAINER =		Abel Abraham Camarillo Ojeda <acamari@verlet.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB += c

.include <bsd.port.mk>
