# $OpenBSD$

     SUBDIR =
     SUBDIR += festvox_don
     SUBDIR += festvox_ellpc11k
     SUBDIR += festvox_kallpc16k
     SUBDIR += festvox_kedlpc16k
     SUBDIR += festvox_rablpc16k

.include <bsd.port.subdir.mk>
