# $OpenBSD$

COMMENT =	two way relationships enhancing node reference fields

DISTNAME = 	noderelationships-6.x-1.5
PKGNAME =	drupal6-noderelationships-1.5
REVISION =	3

RUN_DEPENDS =	www/drupal6/cck \
		www/drupal6/modalframe \
		www/drupal6/views

.include <bsd.port.mk>
