# $OpenBSD$

COMMENT=		Maketext from already interpolated strings

MODULES=		cpan
DISTNAME=		Locale-Maketext-Fuzzy-0.02
REVISION=		0
CATEGORIES=		converters devel
USE_GROFF =		Yes

# GPL
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
