# $OpenBSD$

COMMENT =		perl module implementing simple file locking

MODULES =		cpan
DISTNAME =		LockFile-Simple-0.207
REVISION =		0
CATEGORIES =		devel
USE_GROFF =		Yes

MAINTAINER =		Pierre-Emmanuel Andre <pea@openbsd.org>

# Perl / GPLv2
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

.include <bsd.port.mk>	
