# $OpenBSD$

COMMENT =	GNUstep jigsaw puzzle

DISTNAME =	Jigsaw-0.8
CATEGORIES =	games

HOMEPAGE =	http://gap.nongnu.org/jigsaw/
MASTER_SITES =	${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB +=	c m pthread

.include <bsd.port.mk>
