# $OpenBSD$
#

     SUBDIR =
     SUBDIR += AcePerl
     SUBDIR += AcePerl,opt
     SUBDIR += bioperl
     SUBDIR += emboss
     SUBDIR += nutdb
     SUBDIR += p5-Bio-ASN1-EntrezGene
     SUBDIR += py-biopython

.include <bsd.port.subdir.mk>
