# $OpenBSD$

COMMENT=		talk to other applications

MODULES=		cpan
DISTNAME=		Expect-1.21
REVISION=		0
CATEGORIES=		devel
USE_GROFF =		Yes

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=		devel/p5-IO-Tty>=1.07

.include <bsd.port.mk>
