# $OpenBSD$

COMMENT=	human-readable unit-aware calculator

MODULES=	cpan
DISTNAME=	Math-Calc-Units-1.07
CATEGORIES=	math
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
