# $OpenBSD$

COMMENT =	zap duplicate content through redirects
BROKEN =	drupal7 apache configuration creates loops

DISTNAME = 	globalredirect-7.x-1.4
PKGNAME =	drupal7-globalredirect-1.4

.include <bsd.port.mk>
