# $OpenBSD$

COMMENT=	web based calendar application, for Horde

HORDE_NAME=	Kronolith

# GPLv2
DISTNAME=	kronolith-h3-2.3.6
REVISION=	1
CATEGORIES=	mail

RUN_DEPENDS=	devel/pear-Date \
		www/horde/imp

.include <bsd.port.mk>
