# $OpenBSD$

COMMENT=	C implementation of priority queues

SHARED_ONLY=    Yes

MODULES=	cpan
DISTNAME=	POE-XS-Queue-Array-0.005
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB += c

.include <bsd.port.mk>
