# $OpenBSD$

COMMENT =	file cck field
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	filefield-6.x-3.10
PKGNAME =	drupal6-filefield-3.10

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
