# $OpenBSD$

COMMENT =		simple and pure Perl RSS parser

DISTNAME =		RSS-Parser-Lite-0.10
REVISION =		0
CATEGORIES =		textproc

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM = Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan
USE_GROFF =		Yes
CPAN_AUTHOR =		EBOSRUP

RUN_DEPENDS =		www/p5-SOAP-Lite

.include <bsd.port.mk>
