# $OpenBSD$

COMMENT =	simple configuration file class

MODULES =	cpan
DISTNAME =	Config-Simple-4.59
REVISION =	1
CATEGORIES =	devel
USE_GROFF =	Yes

MAINTAINER =	Mikolaj Kucharski <mikolaj@kucharski.name>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

CPAN_AUTHOR =		SHERZODR
CONFIGURE_STYLE =	perl

.include <bsd.port.mk>
