# $OpenBSD$

COMMENT= 	check for POD errors in files

MODULES=	cpan
DISTNAME=	Test-Pod-1.45
CATEGORIES=	devel

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
