# $OpenBSD$

COMMENT=	view images and do slideshows

DISTNAME=	LaternaMagica-0.3
REVISION=	1

HOMEPAGE=	http://gap.nongnu.org/laternamagica/
MASTER_SITES=	${MASTER_SITE_SAVANNAH:=gap/}

MODULES=	x11/gnustep
WANTLIB+=	c m pthread

.include <bsd.port.mk>
