# $OpenBSD$

SHARED_ONLY =		Yes

COMMENT =		perl interface to OpenBSD socket splicing

DISTNAME =		BSD-Socket-Splice-0.04

CATEGORIES =		net

MAINTAINER =		Alexander Bluhm <bluhm@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

.include <bsd.port.mk>
