# $OpenBSD$

COMMENT=	introspect many-to-many shortcuts

DISTNAME=	DBIx-Class-IntrospectableM2M-0.001001
CATEGORIES=	databases devel

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan

RUN_DEPENDS=		databases/p5-DBIx-Class

.include <bsd.port.mk>
