# $OpenBSD$

SHARED_ONLY=		Yes
COMMENT=		assert performance of perl regexps

MODULES=		cpan
DISTNAME=		Devel-SawAmpersand-0.32
REVISION=		0
CATEGORIES=		devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB += c

.include <bsd.port.mk>
