# $OpenBSD$

COMMENT=		force coercion when validating type constraints

DISTNAME=		MooseX-Meta-TypeConstraint-ForceCoercion-0.01
REVISION=		0

CATEGORIES=		devel

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MODULES=		cpan
USE_GROFF =		Yes

RUN_DEPENDS=		devel/p5-Moose \
			devel/p5-namespace-autoclean

.include <bsd.port.mk>
