# $OpenBSD$

COMMENT =	pure Perl implementation for an XML-RPC client and server

MODULES =	cpan
DISTNAME =	XML-RPC-0.9
CATEGORIES =	net devel

MAINTAINER =	Mikolaj Kucharski <mikolaj@kucharski.name>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

RUN_DEPENDS =		textproc/p5-XML-TreePP

CPAN_AUTHOR =		DAAN
CONFIGURE_STYLE =	perl

.include <bsd.port.mk>
