# $OpenBSD$

COMMENT=	limits the number of forked concurrent processes

DISTNAME=	Proc-Queue-1.23
REVISION=	0
CATEGORIES=	sysutils
MODULES=	cpan
USE_GROFF =	Yes

MAINTAINER=	Okan Demirmen <okan@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
