# $OpenBSD$

COMMENT=	object oriented DBMS for perl

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	Rose-Object-0.856
REVISION=	0
CATEGORIES=	databases devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=	databases/p5-Rose-DateTime

.include <bsd.port.mk>
