# $OpenBSD$

COMMENT=	remove files and directories with perl

MODULES=	cpan

DISTNAME=	File-Remove-1.52
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
