# $OpenBSD$

COMMENT=	little board game

DISTNAME=	GShisen-1.3.0
REVISION =	2
CATEGORIES=	games

HOMEPAGE=	http://gap.nongnu.org/gshisen/
MASTER_SITES=	${MASTER_SITE_SAVANNAH:=gap/}

MODULES=	x11/gnustep
WANTLIB=	c m pthread

.include <bsd.port.mk>
