# $OpenBSD$

COMMENT=	simple means to move data between Perl and PHP

MODULES=	cpan
DISTNAME=	PHP-Serialization-0.33
REVISION=	0
CATEGORIES=     www
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
