# $OpenBSD$

COMMENT =	Fast, Nimble PDF Generation For Ruby - prawn-format

DISTNAME =	prawn-format-0.2.0.1
REVISION =	4

RUN_DEPENDS =		textproc/ruby-prawn/core,${MODRUBY_FLAVOR}

MODRUBY_REGRESS =	rake
REGRESS_DEPENDS =	devel/ruby-echoe,${MODRUBY_FLAVOR} \
			textproc/ruby-prawn/prawn,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
