# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	interface to handy and fast permutation

MODULES=	cpan
DISTNAME=	Algorithm-Permute-0.12
REVISION=	1
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
