# $OpenBSD$

COMMENT=	GkrellM2 load meter with a familiar face

DISTNAME=	gkrellflynn-0.8
REVISION=	8
CATEGORIES=	x11

ALL_TARGET=	gkrellm2

PLUGIN=		${WRKSRC}/gkrellflynn.so

WANTLIB=

.include <bsd.port.mk>
