# $OpenBSD$

     SUBDIR =
     SUBDIR += bibelot
     SUBDIR += coldsync
     SUBDIR += isilo
     SUBDIR += p5-Palm
     SUBDIR += palm-bookmarks
     SUBDIR += palm2ical
     SUBDIR += palmpower
     SUBDIR += pilrc
     SUBDIR += pose

.include <bsd.port.subdir.mk>
