# $OpenBSD$

COMMENT=		less indentation and newlines plus sub deparsing

DISTNAME=		Data-Dumper-Concise-2.020
CATEGORIES=		devel

MAINTAINER=		Andrew Fresh <andrew@cpan.org>

# Same as Perl
PERMIT_PACKAGE_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes

MODULES=		cpan

.include <bsd.port.mk>
