# $OpenBSD$

# edb, epeg and etk are disabled as they need an update.

     SUBDIR =
     SUBDIR += e
     SUBDIR += ecore
     SUBDIR += e_dbus
     SUBDIR += edje
     SUBDIR += eet
     SUBDIR += efreet
     SUBDIR += eina
     SUBDIR += embryo
     SUBDIR += evas

.include <bsd.port.subdir.mk>
