# $OpenBSD$

COMMENT=	Perl module implementing lanman and nt md4 hash functions

MODULES=	cpan
DISTNAME=	Crypt-SmbHash-0.12
REVISION=	2
CATEGORIES=	security
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# same license as perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=	security/p5-Digest-MD4

.include <bsd.port.mk>
