# $OpenBSD$

COMMENT=	inflect short English Phrases

DISTNAME=	Lingua-EN-Inflect-Phrase-0.12
CATEGORIES=	textproc

MAINTAINER=	Andrew Fresh <andrew@cpan.org>

# GPL or Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan
CONFIGURE_ARGS=		--skipdeps

.include <bsd.port.mk>
