# $OpenBSD$

COMMENT =		n64 emulator signal co-processor plugin

# GPLv2+
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB =		m stdc++

MUPEN64PLUS_MOD = 	rsp-hle

.include <bsd.port.mk>
