# $OpenBSD$

COMMENT =	conditionally executed actions based on occurring events
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	rules-7.x-2.2
PKGNAME =	drupal7-rules-2.2
RUN_DEPENDS =	www/drupal7/entity

.include <bsd.port.mk>
