# $OpenBSD$

COMMENT=	X.10 firecracker interface

DISTNAME=	bottlerocket-0.04c
REVISION =	1
CATEGORIES=	comms

HOMEPAGE =	http://www.linuxha.com/bottlerocket/
MASTER_SITES =	${HOMEPAGE}

CONFIGURE_STYLE=gnu

SEPARATE_BUILD= Yes

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB=		c

NO_REGRESS=	Yes

.include <bsd.port.mk>
