# $OpenBSD$

COMMENT=		portable replacement for popen4

DISTNAME=		systemu-2.4.2
CATEGORIES=		devel

HOMEPAGE=		http://rubyforge.org/projects/codeforpeople/

# Ruby license
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
