# $OpenBSD$

COMMENT =	conditionally executed actions based on occurring events
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	rules-6.x-1.4
PKGNAME =	drupal6-rules-1.4
REVISION =	0

.include <bsd.port.mk>
