# $OpenBSD$

    SUBDIR =
    SUBDIR += folks
    SUBDIR += telepathy-farstream
    SUBDIR += telepathy-gabble
    SUBDIR += telepathy-glib
    SUBDIR += telepathy-haze
    SUBDIR += telepathy-idle
    SUBDIR += telepathy-inspector
    SUBDIR += telepathy-logger
    SUBDIR += telepathy-mission-control
    SUBDIR += telepathy-pinocchio
    SUBDIR += telepathy-python
    SUBDIR += telepathy-salut
    SUBDIR += telepathy-spec

.include <bsd.port.subdir.mk>
