# $OpenBSD$

COMMENT =		stream editor
DISTNAME =		sed-4.2.1

#SHARED_LIBS =		???

CATEGORIES =		sysutils

HOMEPAGE =		http://www.gnu.org/software/sed/

# 
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

#WANTLIB =		???

MASTER_SITES =		${MASTER_SITE_GNU:=sed/}

#MODULES =		???
#BUILD_DEPENDS =	???
#RUN_DEPENDS =		???
#LIB_DEPENDS =		???

#MAKE_FLAGS =		???
#MAKE_ENV =		???

SEPARATE_BUILD =	Yes
CONFIGURE_STYLE =	gnu
#CONFIGURE_ARGS +=	${CONFIGURE_SHARED}
#CONFIGURE_ENV =	???

# for gnu stuff
#AUTOCONF_VERSION =	??? (defaults to 2.13)
#AUTOMAKE_VERSION =	??? (defaults to 1.4)
# config.guess and others are copied here
#MODGNU_CONFIG_GUESS_DIRS = ??? (defaults to ${WRKSRC}

#CFLAGS =		???
#LDFLAGS =		???

.include <bsd.port.mk>
