# $OpenBSD$

COMMENT =	drupal views, smart content lists
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	views-7.x-3.3
PKGNAME =	drupal7-views-3.3

RUN_DEPENDS =	www/drupal7/ctools

.include <bsd.port.mk>
