# $OpenBSD$
COMMENT=	handle v-strings (often used as version strings)

MODULES=	cpan
DISTNAME=	Data-VString-0.000004
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
