# $OpenBSD$

COMMENT =	GNUstep battery monitor

DISTNAME =	batmon-0.6
CATEGORIES =	sysutils

HOMEPAGE =	http://gap.nongnu.org/batmon/
MASTER_SITES =	${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB =	c m pthread

.include <bsd.port.mk>
