# $OpenBSD$
COMMENT=	bidirectional Hebrew support

MODULES=	cpan
DISTNAME=	Locale-Hebrew-1.04
REVISION=	2
CATEGORIES=	devel
SHARED_ONLY=	yes
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
