# $OpenBSD$

COMMENT =	create sensible urls automatically
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	pathauto-7.x-1.1
PKGNAME =	drupal7-pathauto-1.1
RUN_DEPENDS =	www/drupal7/token

.include <bsd.port.mk>
