# $OpenBSD$

COMMENT =	extra settings for some themes
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	themesettingsapi-6.x-1.4
PKGNAME =	drupal6-themesettings-1.4
REVISION =	1

.include <bsd.port.mk>
