# $OpenBSD$

COMMENT=	cleans up HTML code for web browsers, not humans

MODULES=	cpan
DISTNAME=	HTML-Clean-0.8
REVISION=	1
CATEGORIES=	www
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
