# $OpenBSD$

COMMENT=	collate XML character events in one chunk

MODULES=	cpan
DISTNAME=	XML-Filter-BufferText-1.01
REVISION=	0
CATEGORIES=	textproc
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=	textproc/p5-XML-SAX

.include <bsd.port.mk>
