# $OpenBSD$

COMMENT= 	expands user directories in paths

MODULES=	cpan 
DISTNAME=	File-Path-Expand-1.02
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
