# $OpenBSD$

COMMENT=	camelcase, de-camelcase

MODULES=	cpan
DISTNAME=	String-CamelCase-0.02
CATEGORIES=	textproc

MAINTAINER=	Andrew Fresh <andrew@cpan.org>

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
