# $OpenBSD$

COMMENT=	library to parse Uniform Resource Identifiers

MODULES=	cpan
DISTNAME=	URI-1.60
CATEGORIES=	www

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
