# $OpenBSD$

COMMENT =	test site as another user
MAINTAINER =	Marc Espie <espie@openbsd.org>
CATEGORIES =	devel

DISTNAME =	masquerade-6.x-1.7
PKGNAME =	drupal6-masquerade-1.7

.include <bsd.port.mk>
