# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	ordered hashes for Perl

DISTNAME=	Tie-Hash-Indexed-0.05
REVISION=	2
CATEGORIES=	devel
MODULES=	cpan
USE_GROFF =	Yes

MAINTAINER=	Okan Demirmen <okan@demirmen.com>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
