# $OpenBSD$

COMMENT =	color strings using ANSI escape sequences

DISTNAME =	term-ansicolor-1.0.4
REVISION =	4
CATEGORIES =	devel

HOMEPAGE =	http://term-ansicolor.rubyforge.org/

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
