# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	sale_opportunity
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account \
			productivity/tryton/product \
			productivity/tryton/sale \
			productivity/tryton/stock

.include <bsd.port.mk>
