# $OpenBSD$

SUBDIR += chora
SUBDIR += dimp
SUBDIR += horde
SUBDIR += imp
SUBDIR += ingo
SUBDIR += kronolith
SUBDIR += mimp
SUBDIR += mnemo
SUBDIR += nag
SUBDIR += turba

.include <bsd.port.subdir.mk>
