# $OpenBSD$

     SUBDIR =
     SUBDIR += asm
     SUBDIR += jBCrypt
     SUBDIR += java-getopt
     SUBDIR += javaPathHelper
     SUBDIR += jlint
     SUBDIR += jna
     SUBDIR += junit

.include <bsd.port.subdir.mk>
