# $OpenBSD$

COMMENT=		implementation of 3DES encryption on ECB mode

MODULES=		cpan
DISTNAME=		Crypt-TripleDES-0.24
REVISION=		1
CATEGORIES=		security
USE_GROFF =		Yes

# Perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>	
