# $OpenBSD$

MODPY_EGG_VERSION =	2.4.1
TRYTOND_MODULE =	account_product
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account \
			productivity/tryton/company \
			productivity/tryton/product

.include <bsd.port.mk>
