# $OpenBSD$

MODPY_EGG_VERSION =	2.4.1
TRYTOND_MODULE =	stock

RUN_DEPENDS =		productivity/tryton/company \
			productivity/tryton/currency \
			productivity/tryton/party \
			productivity/tryton/product

.include <bsd.port.mk>
