# $OpenBSD$

COMMENT= 	render tabular data as plain text

MODULES=	cpan
DISTNAME=	Text-TabularDisplay-1.22
REVISION=	0
CATEGORIES=	textproc devel
USE_GROFF =	Yes

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
