# $OpenBSD$

COMMENT=	perl module to create WML cards

MODULES=	cpan
DISTNAME=	WML-Card-0.02
REVISION=	1
CATEGORIES=	textproc www
USE_GROFF =	Yes

# GPL/Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=	www/p5-HTML-Parser

.include <bsd.port.mk>
