# $OpenBSD$

COMMENT =	database introspection
MAINTAINER =	Marc Espie <espie@openbsd.org>

CATEGORIES += 	devel
DISTNAME = 	schema-6.x-1.7
PKGNAME =	drupal6-schema-1.7
REVISION =	0

.include <bsd.port.mk>
