# $OpenBSD$

     SUBDIR += browser
     SUBDIR += hubbub
     SUBDIR += libcss
     SUBDIR += libnsbmp
     SUBDIR += libnsgif
     SUBDIR += libparserutils
     SUBDIR += libwapcaplet

.include <bsd.port.subdir.mk>
