# $OpenBSD$

COMMENT =	merb-auth support for slices

DISTNAME =	merb-auth-slice-password-1.1.1
REVISION =	1

RUN_DEPENDS =	www/ruby-merb/slices,${MODRUBY_FLAVOR}>=1.1,<2.0 \
		www/ruby-merb/auth-more,${MODRUBY_FLAVOR}>=1.1.1,<1.2 \
		www/ruby-merb/auth-core,${MODRUBY_FLAVOR}>=1.1.1,<1.2

.include <bsd.port.mk>
