# $OpenBSD$

COMMENT =		cubic spline interpolation of data

DISTNAME =		Math-Spline-0.01
REVISION =		0
CATEGORIES =		math

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan
USE_GROFF =		Yes

NO_REGRESS =		Yes

.include <bsd.port.mk>
