# $OpenBSD$

COMMENT =	advanced help system for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	advanced_help-6.x-1.2
PKGNAME =	drupal6-advanced-help-1.2
REVISION =	0

.include <bsd.port.mk>
