# $OpenBSD$

COMMENT=	interface to CDDB and freedb servers

DISTNAME=	CDDB-1.220
REVISION=	0
CATEGORIES=	audio

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=	cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
