# $OpenBSD$

COMMENT =	theme for eCommerce sites with support for Ubercart

DISTNAME = 	at-commerce-7.x-2.0-rc3
PKGNAME =	drupal7-theme-atcommerce-2.0-rc3

MAINTAINER =	Jasper Lievisse Adriaanse <jasper@openbsd.org>

RUN_DEPENDS =	www/drupal7/nodesinblock \
		www/drupal7/theme-adaptivetheme
MODDRUPAL_THEME = Yes

.include <bsd.port.mk>
