# $OpenBSD$

COMMENT=	manipulate IPv4/IPv6 netblocks in CIDR notation

MODULES=	cpan
DISTNAME=	Net-CIDR-0.15
CATEGORIES=	net

MAINTAINER=	Matteo Cantoni <matteo.cantoni@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
