# $OpenBSD$

COMMENT =	override Authoring information and Publishing options

DISTNAME = 	override_node_options-6.x-1.11
PKGNAME =	drupal6-override_node_options-1.11
REVISION =	2

.include <bsd.port.mk>
