# $OpenBSD$

COMMENT =	automatic node titles for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	auto_nodetitle-7.x-1.0
PKGNAME =	drupal7-automatic-nodetitle-1.0

.include <bsd.port.mk>
