# $OpenBSD$

COMMENT=		extracts files from Microsoft CAB archives

DISTNAME=		cabextract-1.3
CATEGORIES=		archivers

HOMEPAGE=		http://www.cabextract.org.uk/

MAINTAINER=		Steve Shockley <steve.shockley@shockley.net>

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB=		c

MASTER_SITES=		${HOMEPAGE}

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
