# $OpenBSD$

COMMENT=	perlish implementation of Java like inner classes

DISTNAME=	Class-Inner-0.1
REVISION=	2
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=cpan

.include <bsd.port.mk>
