# $OpenBSD$

COMMENT= 	find memory cycles in objects

MODULES=	cpan

DISTNAME=	Devel-Cycle-1.11
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
