# $OpenBSD$

COMMENT=		provide a configuration hash with options

DISTNAME=		Config-Options-0.08
REVISION=		0
CATEGORIES=		devel

MODULES=		cpan
USE_GROFF =		Yes

# Artistic License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
