# $OpenBSD$

COMMENT=	integrated Templates for PHP

DISTNAME=	HTML_Template_IT-1.1.3
REVISION=	3
CATEGORIES=	www

MODULES=	www/pear

# Modified BSD license
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
