# $OpenBSD$

COMMENT =	precision raster image convolution engine

DISTNAME =	PRICE-1.0.0
REVISION =	0
CATEGORIES =	graphics

HOMEPAGE =	http://price.sourceforge.net/
MASTER_SITES =	${MASTER_SITE_SOURCEFORGE:=price/}

MODULES =	x11/gnustep
WANTLIB +=	c m pthread

.include <bsd.port.mk>
