# $OpenBSD$

COMMENT=	perl extension for parsing US street addresses
MODULES=	cpan
DISTNAME=	Geo-StreetAddress-US-1.03
CATEGORIES=	geo

# Perl
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

MODCPAN_EXAMPLES=	Yes
MODCPAN_EXAMPLES_DIST=	eg

RUN_DEPENDS=	devel/p5-Class-Data-Inheritable

.include <bsd.port.mk>
