# $OpenBSD$ 
 
     SUBDIR =
     SUBDIR += stable
     SUBDIR += stable,compressed
     SUBDIR += snapshot
     SUBDIR += snapshot,sasl
     SUBDIR += snapshot,compressed,sidebar
     SUBDIR += snapshot,compressed,sidebar,sasl
     SUBDIR += snapshot,compressed,sidebar,sasl,slang

.include <bsd.port.subdir.mk>
