# $OpenBSD$

COMMENT=	read/write data according to a standard Fortran 77 FORMAT

MODULES=	cpan
DISTNAME=	Fortran-Format-0.90
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
