# $OpenBSD$

COMMENT=	convert singular to plural, select a or an

MODULES=	cpan
DISTNAME=	Lingua-EN-Inflect-1.893
CATEGORIES=	textproc

MAINTAINER=	Sam Smith <S@msmith.net>

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODCPAN_EXAMPLES=	Yes
MODCPAN_EXAMPLES_DIST=	demo

.include <bsd.port.mk>
