# $OpenBSD$

COMMENT=	expiry plug-in for Memoize that adds LRU cache expiration

DISTNAME=	Memoize-ExpireLRU-0.55
CATEGORIES=	devel

MAINTAINER=	Andrew Fresh <andrew@cpan.org>

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan

.include <bsd.port.mk>
