# $OpenBSD$

     SUBDIR =
     SUBDIR += chipmunk
     SUBDIR += fritzing
     SUBDIR += geda-gaf
     SUBDIR += gerbv
     SUBDIR += gnucap
     SUBDIR += gtkwave
     SUBDIR += kicad
     SUBDIR += kicad-library
     SUBDIR += klogic
     SUBDIR += necpp
     SUBDIR += ngspice
     SUBDIR += openscad
     SUBDIR += pcb
     SUBDIR += qcad
     SUBDIR += qucs
     SUBDIR += spice
     SUBDIR += xcircuit
     SUBDIR += xnecview
     SUBDIR += xtrkcad

.include <bsd.port.subdir.mk>
