# $OpenBSD$

COMMENT =		GIF decoding library

NETSURF_PROJECT =	libnsgif
NETSURF_VERSION =	0.0.3

WRKDIST =		${WRKDIR}/${DISTNAME}

CATEGORIES =		graphics
SHARED_LIBS =		nsgif 0.0 #0.0.3

.include <bsd.port.mk>
