# $OpenBSD$

COMMENT=	cross-platform path manipulation

MODULES=	cpan
DISTNAME=	Path-Class-0.19
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Simon Bertrang <simon@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CPAN_AUTHOR=	KWILLIAMS

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
