# $OpenBSD$

COMMENT=		extra themes for matchbox

DISTNAME=		matchbox-themes-extra-0.3
REVISION=		0

MASTER_SITES=		${MASTER_SITES_MATCHBOX:=/matchbox-themes-extra/0.3/}

RUN_DEPENDS=		x11/matchbox/matchbox-window-manager

CONFIGURE_STYLE=gnu

.include <bsd.port.mk>
