# $OpenBSD$

     SUBDIR =
     SUBDIR += acx
     SUBDIR += athn
     SUBDIR += bwi
     SUBDIR += ipw
     SUBDIR += iwi
     SUBDIR += iwn
     SUBDIR += malo
     SUBDIR += otus
     SUBDIR += pgt
     SUBDIR += rsu
     SUBDIR += uath
     SUBDIR += ueagle
     SUBDIR += upgt
     SUBDIR += urtwn
     SUBDIR += uvideo
     SUBDIR += wpi

.include <bsd.port.subdir.mk>
