# $OpenBSD$

COMMENT=	sorting of revision-like numbers

MODULES=	cpan
DISTNAME=	Sort-Versions-1.5
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

# GPL/Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
