# $OpenBSD$

COMMENT =	Obscure Linux base packages

VERSION =	0.1
PKGNAME =	obscure-base-${VERSION}

RUN_DEPENDS += \
		databases/db/v4,-main	\
		devel/gmake		\
		devel/libbsd		\
		devel/ncursesw		\
		devel/bmake		\
		editors/vim,no_x11	\
		misc/findutils		\
		sysutils/coreutils	\
		sysutils/jot		\
		sysutils/perl		\
		textproc/mdocml

.include <bsd.port.mk>
