# $OpenBSD$

COMMENT= 	Perl module for creating read/write buffers

MODULES=	cpan
DISTNAME=	Data-Buffer-0.04
REVISION=	1
CATEGORIES=	devel
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
