# $OpenBSD$

COMMENT =	advanced 1/2/3-column theme for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>
DISTNAME=	acquia_marina-6.x-1.9
PKGNAME =	drupal6-theme-acquia-marina-1.9
REVISION =	0

HOMEPAGE =	http://drupal.org/node/357261

MAINTAINER =	Stuart Henderson <sthen@openbsd.org>

MODDRUPAL_THEME = Yes

RUN_DEPENDS =	www/drupal6/themesettingsapi

.include <bsd.port.mk>
