# $OpenBSD$

COMMENT=	module to bubble-babble fingerprints

MODULES=	cpan
DISTNAME=	Digest-BubbleBabble-0.02
CATEGORIES=	security

MAINTAINER=	Peter Stromberg <wilfried@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
