# $OpenBSD$

COMMENT=	provide misc. jQuery plugins

DISTNAME=	jquery_plugin-7.x-1.0
PKGNAME=	drupal7-jquery_plugin-1.0

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

.include <bsd.port.mk>