# $OpenBSD$

COMMENT=	Perl Objects as Hash, Array and Scalar at the same time

MODULES=	cpan
DISTNAME=	Object-MultiType-0.05
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

MAINTAINER=	Okan Demirmen <okan@openbsd.org>

# GPL/Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
