# $OpenBSD$

COMMENT=	German grundform reduction

MODULES=	cpan
DISTNAME=	Text-German-0.06
REVISION=	0
CATEGORIES=	textproc
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
