# $OpenBSD$

COMMENT=		higher-order list utility functions

MODULES=		cpan
DISTNAME=		List-UtilsBy-0.07
CATEGORIES=		textproc

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	modbuild

.include <bsd.port.mk>
