# $OpenBSD$

COMMENT=	date and timezone classes for PHP

DISTNAME=	Date-1.4.7
CATEGORIES=	devel

MODULES=	www/pear

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
