# $OpenBSD$

COMMENT =	library for string essentials
DISTNAME =	libestr-0.1.2
SHARED_LIBS +=  estr                 0.0      # 0.0
CATEGORIES =	devel
REVISION =	1

HOMEPAGE =	http://libestr.adiscon.com/
MAINTAINER =	David Hill <dhill@mindcry.org>

# LGPLv2.1 
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MASTER_SITES =	${HOMEPAGE}/files/download/

USE_LIBTOOL=		Yes

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
