# $OpenBSD$

COMMENT=		env prompter for zoid shell

MODULES=		cpan
DISTNAME=		Env-PS1-0.06
REVISION=		0
CATEGORIES=		devel
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	modbuild

.include <bsd.port.mk>
