# $OpenBSD$

COMMENT =	german translation
EXTRACT_ONLY =

DISTNAME =	de-6.x-1.0
PKGNAME =	drupal6-de-1.0
REVISION =	2

post-extract:
	mkdir -p ${WRKDIST}
	cd ${WRKDIST} && tar zxf ${FULLDISTDIR}/${DISTFILES}

.include <bsd.port.mk>
