# $OpenBSD$

COMMENT =	plugin for the Merb that provides activerecord access

VERSION =	1.0.0.1
DISTNAME =	merb_activerecord-${VERSION}
REVISION =	7

RUN_DEPENDS =	www/ruby-merb/core,${MODRUBY_FLAVOR}>=0.9.9 \
		databases/ruby-activerecord,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
