# $OpenBSD$

COMMENT=	summarize HTML pages

MODULES=	cpan
DISTNAME=	HTML-Summary-0.017
REVISION=	1
CATEGORIES=	textproc
USE_GROFF =	Yes

PERMIT_DISTFILES_CDROM=	No permission
PERMIT_DISTFILES_FTP=	No permission
PERMIT_PACKAGE_CDROM=	No permission
PERMIT_PACKAGE_FTP=	No permission

.include <bsd.port.mk>
