# $OpenBSD$

COMMENT=	memo application, for Horde

HORDE_NAME=	Mnemo

# Horde (BSD-like with some restrictions, see LICENSE)
DISTNAME=	mnemo-h3-2.2.5
REVISION=	1
CATEGORIES=	databases

RUN_DEPENDS=	lang/php/${MODPHP_VERSION},-imap

.include <bsd.port.mk>
