# $OpenBSD$

COMMENT=	implementation of the RC4 encryption algorithm

MODULES=	cpan
DISTNAME=	Crypt-RC4-2.02
REVISION=	1
CATEGORIES=	security
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>	
