# $OpenBSD$

COMMENT=	set default flags on regular expressions

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	Regexp-DefaultFlags-0.01
REVISION=	1
CATEGORIES=	textproc

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
