# $OpenBSD$

COMMENT=	abstraction of various SASL mechanism responses

V=		1.0.4
DISTNAME=	Auth_SASL-${V}
PKGNAME=	pear-Auth-SASL-${V}
REVISION=		0
CATEGORIES=	security

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
