# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	stock_supply
REVISION =		0

RUN_DEPENDS =		productivity/tryton/party \
			productivity/tryton/product \
			productivity/tryton/purchase \
			productivity/tryton/stock

.include <bsd.port.mk>
