# $OpenBSD$

COMMENT=	common utilities for IRC-related tasks

MODULES=	cpan
DISTNAME=	IRC-Utils-0.12
CATEGORIES=	net

MAINTAINER=	Wen Heping <wenheping@gmail.com>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
