# $OpenBSD$

COMMENT=	Abstract class wrapper for Autoloader

MODULES=	cpan
DISTNAME=	Class-MethodMapper-1.0
REVISION=	1
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Sam Smith <S@msmith.net>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
