# $OpenBSD$

COMMENT =	GNUstep mastermind game

DISTNAME =	GMastermind-0.6
CATEGORIES =	games

HOMEPAGE =      http://gap.nongnu.org/gmastermind/
MASTER_SITES =  ${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB +=	c m pthread

.include <bsd.port.mk>
