# $OpenBSD$

COMMENT=	calculate geographic distance from a lat/lon pair
MODULES=	cpan
DISTNAME=	Geo-Inverse-0.05
REVISION=	1
CATEGORIES=	geo
USE_GROFF =	Yes

# Perl
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes

.include <bsd.port.mk>
