# $OpenBSD$

COMMENT =	image cck field
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	imagefield-6.x-3.10
PKGNAME =	drupal6-imagefield-3.10

RUN_DEPENDS =	www/drupal6/filefield

.include <bsd.port.mk>
