# $OpenBSD$

COMMENT=	generate pronounceable passwords

MODULES=	cpan
DISTNAME=	Text-Password-Pronounceable-0.30

CATEGORIES=	security

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

USE_GROFF =	Yes

.include <bsd.port.mk>
