# $OpenBSD$

     SUBDIR =
     SUBDIR += aclock 
     SUBDIR += bgchg
     SUBDIR += flynn 
     SUBDIR += itime
     SUBDIR += kam
     SUBDIR += launch
     SUBDIR += mailwatch
     SUBDIR += mms
     SUBDIR += moon
     SUBDIR += mss
     SUBDIR += reminder
     SUBDIR += shoot
     SUBDIR += stock
     SUBDIR += sun
     SUBDIR += volume
     SUBDIR += weather
     SUBDIR += wireless

.include <bsd.port.subdir.mk>
