# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	PerlIO layer for normalizing line endings

MODULES=	cpan
DISTNAME=	PerlIO-eol-0.14
REVISION=	3
CATEGORIES=	devel 
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB += c

.include <bsd.port.mk>
