# $OpenBSD$

COMMENT=	finding memory leaks in perl XS
SHARED_ONLY=	Yes

MODULES=	cpan
DISTNAME=	Devel-Leak-0.03
REVISION=	3
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

WANTLIB += c

.include <bsd.port.mk>
