# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	module to calculate SHA1 digests

MODULES=	cpan
DISTNAME=	Digest-SHA1-2.13
REVISION=	1
CATEGORIES=	security
USE_GROFF =	Yes

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# Artistic licence
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
