# $OpenBSD$

COMMENT=	calling UNIVERSAL::isa as a function

MODULES=	cpan
DISTNAME=	UNIVERSAL-isa-1.03
PKGNAME=	p5-Universal-isa-1.03
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Simon Bertrang <simon@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=modbuild

.include <bsd.port.mk>
