# $OpenBSD$

COMMENT=		perl module for reading procmail logs

DISTNAME=		Log-Procmail-0.11
REVISION=		1
CATEGORIES=		mail textproc

MAINTAINER=		Anil Madhavapeddy <avsm@openbsd.org>

# GPL/Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan
USE_GROFF =		Yes

.include <bsd.port.mk>
