# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	purchase_shipment_cost

RUN_DEPENDS =		productivity/tryton/carrier \
			productivity/tryton/currency \
			productivity/tryton/stock

.include <bsd.port.mk>
