# $OpenBSD$

COMMENT=		parse, analyze and manipulate LaTeX documents

DISTNAME=		LaTeX-TOM-1.01
CATEGORIES=		textproc

MODULES=		cpan
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	modbuild

.include <bsd.port.mk>
