# $OpenBSD$

COMMENT =	automatic node titles for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	auto_nodetitle-6.x-1.2
PKGNAME =	drupal6-automatic-nodetitle-1.2
REVISION =	0

.include <bsd.port.mk>
