# $OpenBSD$

COMMENT=		implementation of Munkres' solution to Assignment problem

DISTNAME=		Algorithm-Munkres-0.08
CATEGORIES=		devel

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MODULES=		cpan

.include <bsd.port.mk>
