# $OpenBSD$

COMMENT =	GNUstep sudoku generator

DISTNAME =	Sudoku-0.7
REVISION =	1
CATEGORIES =	games

HOMEPAGE =	http://gap.nongnu.org/sudoku/
MASTER_SITES =	${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB +=	c m pthread

.include <bsd.port.mk>
