# $OpenBSD$

COMMENT =		program arguments processing module

DISTNAME =		Getopt-ArgvFile-1.11
PKGNAME =		${DISTNAME:S//p5-/}

CATEGORIES =		devel

# Artistic License
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

MODULES =		cpan

CONFIGURE_STYLE =	perl

.include <bsd.port.mk>
