# $OpenBSD$

COMMENT= 	PerlIO layer to gzip/gunzip

MODULES=	cpan

SHARED_ONLY=	Yes

DISTNAME=	PerlIO-gzip-0.18
REVISION=	4
CATEGORIES=	archivers

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB=	c z

.include <bsd.port.mk>
