# $OpenBSD$

COMMENT=	GNUstep image viewer

DISTNAME=	ImageViewer-0.6.3
REVISION =	1
CATEGORIES=	graphics

HOMEPAGE=	http://freshmeat.net/projects/imageviewer
MASTER_SITES=	http://distfiles.nl/

MODULES=	x11/gnustep
WANTLIB+=	c m pthread

.include <bsd.port.mk>
