# $OpenBSD$

COMMENT=		spider to recover and store images from web pages

MODULES=		cpan
DISTNAME=		HTTP-GetImages-0.343
REVISION=		1
CATEGORIES=		www
USE_GROFF =		Yes

MAINTAINER=		Jasper Lievisse Adriaanse <jasper@openbsd.org>

# Artistic + GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=		www/p5-libwww

.include <bsd.port.mk>
