# $OpenBSD$

COMMENT =	custom teaser and body fields using templates
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	contemplate-6.x-1.2
PKGNAME =	drupal6-contemplate-1.2

.include <bsd.port.mk>
