# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT= 	interface to the Serpent encryption algorithm

MODULES=	cpan
DISTNAME=	Crypt-Serpent-1.01
REVISION=	2
CATEGORIES=	security
USE_GROFF =	Yes

MAINTAINER=	Stephan A. Rickauer <stephan@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
