# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	comma-separated values manipulation routines

DISTNAME=	Text-CSV_XS-0.80
CATEGORIES=	textproc
EXTRACT_SUFX=	.tgz
USE_GROFF =	Yes

MODULES=	cpan
CPAN_AUTHOR=	HMBRAND

MAINTAINER=	David Hill <dhill@openbsd.org>

# GPL/Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
