# $OpenBSD$

COMMENT =		locate directory of original program

DISTNAME =		FindBin-0.0.5
CATEGORIES =		devel
HOMEPAGE =		http://github.com/audreyt/findbin
REVISION =		0

# BSD3
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		lang/ghc
MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
