# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	shared data cache using memory mapped files

MODULES=	cpan
DISTNAME=	Cache-Mmap-0.11
EPOCH=		0
REVISION=	0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB += c

.include <bsd.port.mk>
