# $OpenBSD$

COMMENT =	multi-author documents
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	nodeaccess_userreference-7.x-3.8
PKGNAME =	drupal7-node-access-user-reference-3.8
RUN_DEPENDS =	www/drupal7/references

.include <bsd.port.mk>
