# $OpenBSD$

MODPY_EGG_VERSION =	2.4.1
TRYTOND_MODULE =	analytic_invoice
REVISION =		1

RUN_DEPENDS =		productivity/tryton/account_invoice \
			productivity/tryton/analytic_account

.include <bsd.port.mk>
