# $OpenBSD$

COMMENT=		use other catalog formats in Locale::Maketext

MODULES=		cpan
DISTNAME=		Locale-Maketext-Lexicon-0.47
REVISION=		0
CATEGORIES=		devel
USE_GROFF =		Yes

# GPL
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
