# $OpenBSD$

COMMENT=	perl extension for writing XML documents

DISTNAME=	XML-Writer-0.615
CATEGORIES=	textproc

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# MIT
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=	cpan
USE_GROFF =	Yes
MODCPAN_EXAMPLES=	Yes

.include <bsd.port.mk>
