# $OpenBSD$

COMMENT=	generic configuration parser, inspired by apache

MODULES=	cpan
DISTNAME=	Config-General-2.50
CATEGORIES=	devel
HOMEPAGE=	http://www.daemon.de/ConfigGeneral

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
