# $OpenBSD$

COMMENT=	XML parsing class based on PHP's bundled expat

DISTNAME=	XML_Parser-1.2.6
REVISION =	2
CATEGORIES=	textproc

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
