# $OpenBSD$

COMMENT=	print out each line before it is executed

MODULES=	cpan
DISTNAME=	Devel-Trace-0.11
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

# wants press enter to continue
REGRESS_IS_INTERACTIVE=	Yes

.include <bsd.port.mk>
