# $OpenBSD: ports/devel/pear-Date-Holidays/Brazil/Makefile,v 1.3 2012/01/16 22:12:36 sthen Exp $

COMMENT =	Brazilian holiday classes for PHP
HOLNAME =	Brazil-0.1.2
REVISION =	0

.include <bsd.port.mk>
