# $OpenBSD$

     SUBDIR =
     SUBDIR += core
     SUBDIR += conch
     SUBDIR += lore
     SUBDIR += mail
     SUBDIR += names
     SUBDIR += news
     SUBDIR += pair
     SUBDIR += runner
     SUBDIR += web
     SUBDIR += web2
     SUBDIR += words

.include <bsd.port.subdir.mk>
