# $OpenBSD$

COMMENT=	grammar-based, user-friendly config parser

MODULES=	cpan
DISTNAME=	Config-Grammar-1.10
REVISION=	0
CATEGORIES=     devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
