# $OpenBSD$

SHARED_ONLY=		Yes

COMMENT=		set up array elements as aliases

DISTNAME=		Array-RefElem-1.00
REVISION=		0
CATEGORIES=		devel

# perl
PERMIT_PACKAGE_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes

WANTLIB += c

MODULES=		cpan

USE_GROFF=		Yes

.include <bsd.port.mk>
