# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	stock_forecast
REVISION =		0

RUN_DEPENDS =		productivity/tryton/company \
			productivity/tryton/product \
			productivity/tryton/stock

.include <bsd.port.mk>
