# $OpenBSD$

COMMENT=	fast compression for waveform files

DISTNAME=	shorten-3.6.1
CATEGORIES=	audio archivers
HOMEPAGE=	http://www.etree.org/shnutils/shorten/

MAINTAINER=	Christian Weisgerber <naddy@openbsd.org>

PERMIT_PACKAGE_CDROM=	no fee
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	no fee
PERMIT_DISTFILES_FTP=	Yes

WANTLIB=	c m

MASTER_SITES=	${HOMEPAGE}dist/src/

CONFIGURE_STYLE=gnu

.include <bsd.port.mk>
