# $OpenBSD$

COMMENT=                create accessor methods in caller's package

DISTNAME=               accessors-1.01
REVISION=		1
CATEGORIES=             devel

# Artistic/GPL
PERMIT_PACKAGE_FTP=     Yes
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_DISTFILES_FTP=   Yes
PERMIT_DISTFILES_CDROM= Yes

CONFIGURE_STYLE=        modbuild

MODULES=                cpan
USE_GROFF =		Yes
CPAN_AUTHOR=            SPURKIS

.include <bsd.port.mk>
