# $OpenBSD$
#

     SUBDIR =
     SUBDIR += algotutor
     SUBDIR += anki
     SUBDIR += drgeo
     SUBDIR += drgeo-doc
     SUBDIR += dvorak7min
     SUBDIR += edict
     SUBDIR += epte
     SUBDIR += gamgi
     SUBDIR += gtypist
     SUBDIR += verbiste

.include <bsd.port.subdir.mk>
