# $OpenBSD$

COMMENT=	network socket interface support for PHP

DISTNAME=	Net_Socket-1.0.10
REVISION=		0
CATEGORIES=	net

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
