# $OpenBSD$

COMMENT=		module to split text into sentences

MODULES=		cpan
DISTNAME=		Lingua-EN-Sentence-0.25
CATEGORIES=		textproc

# Perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
