# $OpenBSD$

SHARED_ONLY =	Yes
COMMENT =	scope guards, lighter alternative

MODULES =	cpan
DISTNAME =	Guard-1.021
CATEGORIES =	devel
CPAN_AUTHOR = 	MLEHMANN
USE_GROFF =	Yes


# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

.include <bsd.port.mk>
