# $OpenBSD$

COMMENT=        hexadecimal dumper

MODULES=	cpan
DISTNAME=	Data-HexDump-0.02
REVISION=	0
CATEGORIES=     devel
USE_GROFF =	Yes

MAINTAINER=	Abel Abraham Camarillo Ojeda <acamari@the00z.org>

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
