# $OpenBSD$

# It's intended that this list isn't sorted alphabetically.
# Please keep it that way. Thanks.

    SUBDIR =
    SUBDIR += core

    SUBDIR += format
    SUBDIR += layout

    SUBDIR += prawn

.include <bsd.port.subdir.mk>
