# $OpenBSD$

COMMENT =	automatically set and update columns

MODULES =	cpan
DISTNAME =	DBIx-Class-DynamicDefault-0.03
CATEGORIES =	databases

# same as perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

RUN_DEPENDS =	databases/p5-DBIx-Class

REGRESS_DEPENDS =	databases/p5-DBICx-TestDatabase

.include <bsd.port.mk>
