# $OpenBSD$

COMMENT=	CPU load monitor

DISTNAME=	TimeMon-4.1
REVISION =	0
CATEGORIES=	sysutils

HOMEPAGE=	http://gap.nongnu.org/timemon/
MASTER_SITES=	${MASTER_SITE_SAVANNAH:=gap/}

MODULES=	x11/gnustep
WANTLIB=	c m pthread

.include <bsd.port.mk>
