# $OpenBSD$

COMMENT=	stack of free/open source CAD/EDA tools (gEDA suite)

PKGNAME=	geda-0.1

HOMEPAGE=	http://www.gpleda.org/

RUN_DEPENDS=	cad/geda-gaf \
		cad/gerbv \
		cad/gnucap \
		cad/gtkwave \
		cad/ngspice \
		cad/pcb \
		lang/iverilog

.include <bsd.port.mk>
