# $OpenBSD$

     SUBDIR =
     SUBDIR += c2t
     SUBDIR += cconv
     SUBDIR += cless
     SUBDIR += crxvt
     SUBDIR += hc
     SUBDIR += libchewing
     SUBDIR += libtabe
     SUBDIR += lunar
     SUBDIR += py-zhCodecs
     SUBDIR += ttfm

.include <bsd.port.subdir.mk>
