# $OpenBSD$

COMMENT =	GNUstep sticky notes

DISTNAME =	Affiche-0.6.0
REVISION =	1

HOMEPAGE =	http://www.collaboration-world.com/affiche/
MASTER_SITES =	http://www.collaboration-world.com/affiche.data/releases/Stable/

MODULES =	x11/gnustep
WANTLIB +=	c m pthread

WRKDIST =	${WRKDIR}/Affiche

.include <bsd.port.mk>
