# $OpenBSD$

COMMENT =	finds out which version of Perl modules are installed

MODULES =	cpan
DISTNAME =	Module-Which-0.0207
CATEGORIES =	devel

MAINTAINER =	Okan Demirmen <okan@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM = Yes
PERMIT_DISTFILES_FTP =	Yes

RUN_DEPENDS =	devel/p5-String-Truncate

.include <bsd.port.mk>
