# $OpenBSD$

COMMENT =	support multimethods and function overloading in Perl

MODULES =	cpan
DISTNAME =	Class-Multimethods-1.70
REVISION =	0
CATEGORIES =	devel
USE_GROFF =	Yes

MAINTAINER =	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

.include <bsd.port.mk>
