# $OpenBSD$

COMMENT=	Perl interface to the PH protocol

DISTNAME=	Net-PH-2.21
REVISION=	0
CATEGORIES=	net
MODULES=	cpan
USE_GROFF =	Yes

MAINTAINER=	Vijay Ramesh <vramesh2@uiuc.edu>

# Perl License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
