# $OpenBSD$

     SUBDIR =
     SUBDIR += 9libs
     SUBDIR += 9menu
     SUBDIR += 9wm
     SUBDIR += drawterm
     SUBDIR += larswm
     SUBDIR += plan9port
     SUBDIR += rc
     SUBDIR += rc,editline
     SUBDIR += rc,readline
     SUBDIR += sam
     SUBDIR += tcs
     SUBDIR += u9fs
     SUBDIR += w9wm
     SUBDIR += wily

.include <bsd.port.subdir.mk>
