# $OpenBSD$

COMMENT =	JSON converter that Does What I Want
SHARED_ONLY =	Yes

MODULES =	cpan
USE_GROFF =	Yes
DISTNAME =	JSON-DWIW-0.40
REVISION =	1
CATEGORIES =	converters

MAINTAINER =	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

.include <bsd.port.mk>
