# $OpenBSD$

COMMENT=	manipulates e-mail alias files of various formats

DISTNAME=	Mail-Alias-1.12
REVISION=	1
CATEGORIES=	mail

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=	cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
