# $OpenBSD$

VERSION =		2.7
PATCHLEVEL =		.3
REVISION =		0
SHARED_LIBS =		python2.7 0.0
VERSION_SPEC =		>=2.7,<2.8

AUTOCONF_VERSION =	2.67
CONFIGURE_ARGS +=	--with-cxx_main \
			--with-system-expat

.include <bsd.port.mk>
