# $OpenBSD$

COMMENT=	extends require to work on variables

V=		0.13
MODULES=	cpan
DISTNAME=	UNIVERSAL-require-${V}
PKGNAME=	p5-Universal-require-${V}
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
