#	$OpenBSD$

COMMENT=	store multiple values per key

DISTNAME=	Tie-Hash-MultiValue-1.02
REVISION=	0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
