# $OpenBSD$

COMMENT =	extended TicTacToe game for GNUstep

DISTNAME =	Gomoku-1.2.9
REVISION =	1
CATEGORIES =	games

HOMEPAGE =	http://www.gnustep.it/nicola/Applications/Gomoku/
MASTER_SITES =	${HOMEPAGE}

MODULES =	x11/gnustep
WANTLIB += 	c m pthread

.include <bsd.port.mk>
