# $OpenBSD$

COMMENT=		ensure that a platform has weaken support

MODULES=		cpan
DISTNAME=		Task-Weaken-1.03
REVISION=		0
CATEGORIES=		devel
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

CPAN_AUTHOR=		ADAMK

.include <bsd.port.mk>
