# $OpenBSD$

COMMENT =	dependency-injection/inversion-of-control container for Ruby

DISTNAME =	needle-1.3.0
REVISION =	5
CATEGORIES =	devel

# bsd/ruby
PERMIT_PACKAGE_CDROM =		yes
PERMIT_PACKAGE_FTP =		yes
PERMIT_DISTFILES_CDROM =	yes
PERMIT_DISTFILES_FTP =		yes

MODULES =	lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
