# $OpenBSD$

COMMENT =	parse and format SQLite dates and times

MODULES =	cpan
DISTNAME =	DateTime-Format-SQLite-0.11
CATEGORIES =	devel

# same as perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

RUN_DEPENDS =	devel/p5-DateTime \
		devel/p5-DateTime-Format-Builder

.include <bsd.port.mk>
