# $OpenBSD$

COMMENT =	using and creating application 'slices'

DISTNAME =	merb-slices-${VERSION}
REVISION =	1

RUN_DEPENDS =	www/ruby-merb/core,${MODRUBY_FLAVOR}${MERB_REL_VER_SPEC}

.include <bsd.port.mk>
