# $OpenBSD$

COMMENT=	Perl extension for rounding numbers

MODULES=	cpan
DISTNAME=	Math-Round-0.06
REVISION=	0
CATEGORIES=	math
USE_GROFF =	Yes

MAINTAINER=	Steven Mestdagh <steven@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
