# $OpenBSD$

    SUBDIR =
    SUBDIR += cogl
    SUBDIR += core
    SUBDIR += clutter-box2d
    SUBDIR += clutter-gst
    SUBDIR += clutter-gtk
#    SUBDIR += clutter-vala
#    SUBDIR += pyclutter	Doesn't work yet (makes python crash)

.include <bsd.port.subdir.mk>
