# $OpenBSD$

VERSION =		0.9.88
COMMENT =		kde frontend to moc
DISTNAME =		automoc4-${VERSION}
MASTER_SITES?=	${MASTER_SITE_KDE:=stable/automoc4/${VERSION}/}

WANTLIB +=	c m pthread stdc++

.include <bsd.port.mk>
