# $OpenBSD$

COMMENT =	modification of UTF-7 encoding for IMAP

DISTNAME =	Encode-IMAPUTF7-1.03
REVISION =	0
CATEGORIES =	converters
MODULES =	cpan
USE_GROFF =	Yes

MAINTAINER =	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

REGRESS_DEPENDS =	devel/p5-Test-NoWarnings

.include <bsd.port.mk>
