# $OpenBSD$

COMMENT =	library for finding files in a set of paths

DISTNAME =	hike-1.2.1
REVISION =	0
CATEGORIES =	devel	

HOMEPAGE =	https://github.com/sstephenson/hike

# MIT
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

MODULES =	lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
