# $OpenBSD$

COMMENT=		encode characters for LaTeX formatting

DISTNAME=		LaTeX-Encode-0.03
CATEGORIES=		textproc

MODULES=		cpan

# MIT
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

REGRESS_DEPENDS=	devel/p5-Test-Pod-Coverage>=1.08p1

.include <bsd.port.mk>
