# $OpenBSD$

SUBDIR =
SUBDIR += stable
SUBDIR += stable,ldap
SUBDIR += stable,mysql
SUBDIR += stable,pgsql
SUBDIR += stable,sasl2

SUBDIR += snapshot
SUBDIR += snapshot,ldap
SUBDIR += snapshot,mysql
SUBDIR += snapshot,pgsql
SUBDIR += snapshot,sasl2

.include <bsd.port.subdir.mk>
