# $OpenBSD$

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	sale
REVISION =		0

RUN_DEPENDS =		productivity/tryton/account \
			productivity/tryton/account_invoice \
			productivity/tryton/account_product \
			productivity/tryton/product \
			productivity/tryton/stock

.include <bsd.port.mk>
