# $OpenBSD$

COMMENT =	GNUstep minesweeper game

DISTNAME =	GMines-0.2
REVISION =	1
CATEGORIES =	games

HOMEPAGE =	http://gap.nongnu.org/gmines/
MASTER_SITES =	${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB +=	c m pthread

.include <bsd.port.mk>
