# $OpenBSD$

COMMENT=	IPv4 address handling tools for PHP

DISTNAME=	Net_IPv4-1.3.4
CATEGORIES=	net

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

PKG_ARCH=	*

.include <bsd.port.mk>
