# $OpenBSD$

     SUBDIR =
     SUBDIR += festvox_cmu_us_awb_arctic_hts
     SUBDIR += festvox_cmu_us_bdl_arctic_hts
     SUBDIR += festvox_cmu_us_jmk_arctic_hts
     SUBDIR += festvox_cmu_us_slt_arctic_hts
     SUBDIR += festvox_cstr_us_awb_arctic_multisyn
     SUBDIR += festvox_cstr_us_jmk_arctic_multisyn

.include <bsd.port.subdir.mk>
