# $OpenBSD$

SHARED_ONLY =	Yes

COMMENT =	argument type classification

MODULES =	cpan
DISTNAME =	Params-Classify-0.013
CATEGORIES =	devel

# same as perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
