# $OpenBSD$

COMMENT=	parse a cron entry and check against current time

MODULES=	cpan
DISTNAME=	DateTime-Cron-Simple-0.2
REVISION=	0
CATEGORIES=	devel
USE_GROFF =	Yes

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
