# $OpenBSD$

COMMENT =	disable specific messages shown to end users

DISTNAME = 	disable_messages-7.x-1.0
PKGNAME =	drupal7-disable_messages-1.0

MAINTAINER =	Jasper Lievisse Adriaanse <jasper@openbsd.org>

.include <bsd.port.mk>
