# $OpenBSD$

COMMENT =		2-letter, 3-letter, and numerical codes for countries

DISTNAME =		Geography-Countries-2009041301
REVISION =		0
CATEGORIES =		geo devel

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
