# $OpenBSD$

COMMENT =	friendly JRuby interface to Swing

DISTNAME =	${PKGNAME}-jruby
PKGNAME =	profligacy-1.0
CATEGORIES =	x11

# Ruby
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

MODULES =	lang/ruby
FLAVORS =	jruby
FLAVOR =	jruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
