# $OpenBSD$

COMMENT =	light-weight, customizable lightbox plugin

DISTNAME = 	colorbox-7.x-1.3
PKGNAME =	drupal7-colorbox-1.3

MAINTAINER =	Jasper Lievisse Adriaanse <jasper@openbsd.org>

.include <bsd.port.mk>
