# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	implementation of the want command

MODULES=	cpan
DISTNAME=	Want-0.18
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CPAN_AUTHOR=	ROBIN

.include <bsd.port.mk>
