# $OpenBSD$

COMMENT=	compare perl data structures

DISTNAME=	Data-Compare-1.22
CATEGORIES=	devel

MAINTAINER=	Andrew Fresh <andrew@cpan.org>

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		cpan
RUN_DEPENDS=		devel/p5-File-Find-Rule

.include <bsd.port.mk>
