# $OpenBSD$

COMMENT=		simple but non-blocking HTTP/HTTPS client

DISTNAME=		AnyEvent-HTTP-1.46
REVISION=		0
CATEGORIES=		databases devel

MODULES=		cpan

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=		devel/p5-AnyEvent

.include <bsd.port.mk>
