# $OpenBSD$

COMMENT=	perl module for reading and writing DAAP structures

MODULES=	cpan
DISTNAME=	Net-DAAP-DMAP-1.26
REVISION=	0
CATEGORIES=	net
USE_GROFF =	Yes

# same as perl
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

.include <bsd.port.mk>
