# $OpenBSD$

COMMENT =	date cck and api for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	date-7.x-2.5
PKGNAME =	drupal7-date-2.5

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
