# $OpenBSD$

COMMENT=	simple and flexible way to build nice URLs

DISTNAME=	Net_URL_Mapper-0.9.0
REVISION=		0
CATEGORIES=	net

MODULES=	www/pear

# BSD License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=		net/pear-Net-URL

.include <bsd.port.mk>
