# $OpenBSD$

COMMENT =	object oriented interface to create salted hashes

MODULES =	cpan
DISTNAME =	Crypt-SaltedHash-0.06
CATEGORIES =	security
USE_GROFF =	Yes

MAINTAINER =	Jim Razmus II <jim@bonetruck.org>

CPAN_AUTHOR =	ESSKAR

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

.include <bsd.port.mk>
