# $OpenBSD$

COMMENT=		module for dealing with time periods

MODULES=		cpan
DISTNAME=		Period-1.20
PKGNAME=		p5-Time-${DISTNAME}
REVISION =		1
CATEGORIES=		devel
USE_GROFF =		Yes

# Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=Time/}

.include <bsd.port.mk>	
