# $OpenBSD$

COMMENT=	contact management module, for Horde

# Horde license (BSD-like with some restrictions, see LICENSE)
DISTNAME=	turba-h3-2.3.6
REVISION=	1

RUN_DEPENDS=	www/horde/imp

.include <bsd.port.mk>
