# $OpenBSD$

COMMENT =	create SOCKS v4/v5 client or server

DISTNAME =	IO-Socket-Socks-0.61

CATEGORIES =	net
CPAN_AUTHOR =	OLEG

MAINTAINER =	Nigel Taylor <nigel@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =	cpan

MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
