# $OpenBSD$

COMMENT =	create sensible urls automatically
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	pathauto-6.x-1.6
PKGNAME =	drupal6-pathauto-1.6
RUN_DEPENDS =	www/drupal6/token

.include <bsd.port.mk>
