# $OpenBSD$

COMMENT=	justify strings to various alignment styles

MODULES=	cpan
DISTNAME=	Text-Aligner-0.07
CATEGORIES=	textproc
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
