# $OpenBSD$

COMMENT=	popup tree widget

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	HTML-PopupTreeSelect-1.6
REVISION=	0

CATEGORIES=	www

# Perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

RUN_DEPENDS=	www/p5-HTML-Template

.include <bsd.port.mk>
