# $OpenBSD$

COMMENT =	implementation of the RC5 encryption algorithm

MODULES =	cpan
DISTNAME =	Crypt-RC5-2.00
CATEGORIES =	security

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM = Yes
PERMIT_DISTFILES_FTP =	Yes

.include <bsd.port.mk>	
