# $OpenBSD$

COMMENT=		template extension for calling class methods

MODULES=		cpan
DISTNAME=		Template-Plugin-Class-0.14
CATEGORIES=		textproc
USE_GROFF =		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=		textproc/p5-Template

.include <bsd.port.mk>
