# $OpenBSD$

SHARED_ONLY=	Yes

COMMENT=	interface to md5 message-digest algorithm

MODULES=	cpan
DISTNAME=	MD5-1.7
REVISION=	2
CATEGORIES=	security
USE_GROFF =	Yes

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
