# $OpenBSD$

    SUBDIR =
    SUBDIR += core
    SUBDIR += plugins-base
    SUBDIR += plugins-good
    SUBDIR += plugins-libav
    SUBDIR += plugins-ugly
    SUBDIR += plugins-bad

.include <bsd.port.subdir.mk>
