# $OpenBSD$

COMMENT =	fine-grained access control
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	content_access-6.x-1.2
PKGNAME =	drupal6-content-access-1.2
REVISION =	0

.include <bsd.port.mk>
