# $OpenBSD$

COMMENT=	computing subnets in large scale networks

MODULES=	cpan
DISTNAME=	Net-Subnets-0.21
REVISION=	0
CATEGORIES=	net
USE_GROFF =	Yes

MAINTAINER=	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
