# $OpenBSD$

COMMENT=	commandline execution interface

DISTNAME=	System_Command-1.0.7
REVISION=		0
CATEGORIES=	devel

MODULES=	www/pear

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
