# $OpenBSD$

SHARED_ONLY=		Yes

COMMENT=		unbless perl objects

DISTNAME=		Acme-Damn-0.04
CATEGORIES=		devel

MODULES=		cpan
USE_GROFF=		Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

REGRESS_DEPENDS=	devel/p5-Test-Exception

.include <bsd.port.mk>
