# $OpenBSD$

COMMENT=		general user documentation for GNOME

GNOME_PROJECT=		gnome-user-docs
GNOME_VERSION=		3.4.2

# CC Attribution 3.0
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=		x11/gnome

MODGNOME_TOOLS= 	yelp

PKG_ARCH=		*
USE_LIBTOOL=		No

.include <bsd.port.mk>
