# $OpenBSD$

COMMENT = 	show modules your program loads
DISTNAME =	Devel-TraceUse-2.06

CATEGORIES =	devel

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES = 		cpan
CONFIGURE_STYLE = 	modbuild

.include <bsd.port.mk>
